import {useState} from 'react';
import {useStore} from '../store';
import {api} from '../services/api';
import type {Config} from '../types';
export function Settings({close}:{close:()=>void}){
 const original=useStore(s=>s.config);const [cfg,setCfg]=useState<Config|null>(original),[error,setError]=useState('');if(!cfg)return null;
 const number=(key:keyof Config,label:string,min:number,max:number,step=1)=><label key={key}>{label}<input type="number" value={cfg[key] as number} min={min} max={max} step={step} onChange={e=>setCfg({...cfg,[key]:+e.target.value})}/></label>;
 const check=(key:keyof Config,label:string)=><label className="check" key={key}><input type="checkbox" checked={cfg[key] as boolean} onChange={e=>setCfg({...cfg,[key]:e.target.checked})}/>{label}</label>;
 return <div className="modal-backdrop"><form className="settings" onSubmit={async e=>{e.preventDefault();try{const c=await api('/config',cfg);useStore.getState().set({config:c});close();}catch(err){setError(String(err));}}}><h2>CONSOLE CONFIGURATION<button type="button" onClick={close}>CLOSE ×</button></h2><p className="note">Stop the stream before applying settings. Changes take effect in the next session.</p><fieldset><legend>MODEL / INFERENCE</legend><label className="wide">MODEL PATH<input value={cfg.model_path} onChange={e=>setCfg({...cfg,model_path:e.target.value})}/></label>{number('confidence_threshold','CONFIDENCE',.05,.99,.01)}{number('iou_threshold','NMS IOU',.1,.95,.01)}{number('image_size','IMAGE SIZE',320,1920,32)}<label>DEVICE<select value={cfg.device} onChange={e=>setCfg({...cfg,device:e.target.value})}><option value="cpu">CPU</option><option value="0">CUDA 0</option><option value="1">CUDA 1</option></select></label></fieldset>
 <fieldset><legend>TRACKER</legend><label>ALGORITHM<select value={cfg.tracker} onChange={e=>setCfg({...cfg,tracker:e.target.value})}><option value="bytetrack">ByteTrack</option><option value="botsort">BoT-SORT</option></select></label>{number('track_buffer','BUFFER (PROCESSED FRAMES)',1,300)}{number('match_threshold','MATCH THRESHOLD',.1,.99,.01)}{number('trajectory_length','TRAJECTORY POINTS',2,300)}</fieldset>
 <fieldset><legend>PERFORMANCE / DISPLAY</legend>{number('target_fps','TARGET FPS',1,60)}{number('frame_skip','SKIP FRAMES',0,10)}{number('max_frame_width','MAX FRAME WIDTH',320,1920)}{number('jpeg_quality','JPEG QUALITY',40,95)}{number('line_thickness','LINE THICKNESS',.5,4,.5)}{number('zoom','DIGITAL ZOOM',2,4)}{check('show_boxes','Brackets')}{check('show_ids','Track IDs')}{check('show_confidence','Confidence')}{check('show_trajectory','Trajectories')}{check('fade_points','Fade older points')}{check('show_crosshair','Reticle')}{check('show_seeker','Seeker view')}{check('debug','Debug detections')}{check('research_mode','Research panel')}</fieldset>{error&&<p className="error" role="alert">{error}</p>}<button className="primary" type="submit">APPLY SETTINGS</button></form></div>;
}
